[package]
name = "__neighborhood_project"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
slint = "1.11.0"

[build-dependencies]
slint-build = "1.11.0"
