component MenuItem {
    in property <string> text;
    in property <bool> selected;

    Rectangle {
        background: selected ? #3a443b : transparent;

        Text {
            text: text;
            color: white;
        }
    }
}

component TimerInput {
    out property <int> input;
    callback create;

    TextInput {
        input-type: number;
        edited => { input = self.text.to-float(); }
        accepted => { create(); }
    }
}

component Timer {
    in property <int> time;
    callback timeout;

    Rectangle {
        background: time > 2000 ? #3a443b : #5c3737;

        Text {
            text: time;
            horizontal-alignment: left;
        }
    }
}

export component App inherits Window {
    in property <[int]> timers: [1000, 2000, 3000];
    
    property <bool> menu: false;
    in property <[string]> presets: ["Preset 1", "Preset 2", "Preset 3"];
    property <int> selected: 0;
    
    callback close;
    callback create;

    function sel_left() { selected = Math.mod((selected - 1), 3); }
    function sel_right() { selected = Math.mod((selected + 1), 3); }

    FocusScope {
        key-pressed(event) => {
            if (event.text == Key.LeftArrow) {
                sel_left();
            } else if (event.text == Key.RightArrow) {
                sel_right();
            }
            accept
        }

        VerticalLayout {
            for i in timers: Timer {
                time: i;
                timeout => { close(); }
            }
        }
    }
}